# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\cj_edit_student_info_1.har
import Parameters as Parameters
import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCjEditStudentInfo1(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {}
        )
    )
    def test_start(self, param):
        super(TestCaseCjEditStudentInfo1, self).test_start()

    config = (Config("testcase description")
              .verify(False)
              )

    teststeps = [
        Step(
            RunRequest("/loginByMobile.do")
            .post("http://pre-exam.yzou.cn/loginByMobile.do")
            .with_headers(
                **{
                    "Host": "pre-exam.yzou.cn",
                    "Content-Length": "62",
                    "transferId": "463bd48fe5bf43d187cecb9246d8bb9b",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "uri": "http://pre-exam.yzou.cn/toLogin.do",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "title": "%E8%BF%9C%E6%99%BA%E6%95%99%E8%82%B2%E4%BA%91%E6%95%99%E5%AD%A6%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "transferSeq": "1",
                    "X-Requested-With": "XMLHttpRequest",
                    "sendTime": "1597033267549",
                    "Origin": "http://pre-exam.yzou.cn",
                    "Referer": "http://pre-exam.yzou.cn/toLogin.do",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                }
            )
            .with_data(
                {
                    "isOpenImage": "",
                    "mobile": "13560148201",
                    "ImgValidCode": "",
                    "validCode": "888888",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "00")
            .assert_equal("body.body", "SUCCESS")
            .assert_contains()
        )
    ]


if __name__ == "__main__":
    TestCaseCjEditStudentInfo1().test_start()
