# NOTE: Generated By HttpRunner v3.1.4
# FROM: login.har
import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase,Parameters


class TestCaseLogin(HttpRunner):
    @pytest.mark.parametrize("param",Parameters({"mobile": [13560148201], "validCode": [888888],"code":["00"]}),)
    def test_start(self, param):
        super().test_start(param)

    config = (Config("正向用例：测试登录接口功能测试>>loginByMobile.do").verify(False).base_url("${ENV(BASE_URL)}"))

    teststeps = [
        Step(
            RunRequest("测试接口：/loginByMobile.do")
            .post("/loginByMobile.do")
            .with_headers(
                **{
                    "Host": "pre-bms.yzwill.cn",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                }
            )
            .with_data(
                {
                    "isOpenImage": "",
                    "mobile": "$mobile",
                    "ImgValidCode": "",
                    "validCode": "$validCode",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "$code")

        )
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
